-- Migration number: 0001 	 2026-06-20T03:23:37.625Z
-- Full profiles table for PilotRecognition — single batch onboarding

CREATE TABLE IF NOT EXISTS profiles (
  id TEXT PRIMARY KEY,
  auth0_id TEXT NOT NULL UNIQUE,
  email TEXT NOT NULL,
  display_name TEXT,
  first_name TEXT,
  last_name TEXT,
  full_name TEXT,
  phone TEXT,
  date_of_birth TEXT,
  nationality TEXT,
  current_occupation TEXT,
  current_level TEXT,
  current_flight_hours REAL,
  total_flight_hours REAL,
  mentorship_hours REAL,
  foundation_progress REAL,
  overall_recognition_score REAL,
  license_id TEXT,
  country_of_license TEXT,
  license_issuing_authority TEXT,
  ratings TEXT,
  license_types TEXT,
  type_ratings TEXT,
  aircraft_types TEXT,
  aircraft_rated_on TEXT,
  employment_status TEXT,
  unemployed_duration TEXT,
  current_job TEXT,
  career_goal TEXT,
  pilot_stage TEXT,
  elp_level TEXT,
  origin_jurisdiction TEXT,
  is_enrolled_in_foundational INTEGER DEFAULT 0,
  role TEXT DEFAULT 'mentee',
  status TEXT DEFAULT 'active',
  subscription_tier TEXT DEFAULT 'free',
  subscription_status TEXT,
  subscription_start_date TEXT,
  subscription_end_date TEXT,
  profile_image_url TEXT,
  profile_image_public_id TEXT,
  wallet_id TEXT,
  wallet_email TEXT,
  wallet_did TEXT,
  referral_code TEXT,
  pilot_id TEXT UNIQUE,
  dca_agreed INTEGER DEFAULT 0,
  dca_agreed_at TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);
